#!/usr/bin/env python3
"""
Funnel Analyst — Weekly conversion metrics and recommendations
"""
import os
from datetime import datetime
from notion_client import Client
from collections import defaultdict
from pathlib import Path

NOTION_API_KEY = os.getenv("NOTION_API_KEY")
NOTION_DB_ID = os.getenv("NOTION_DB_ID")

notion = Client(auth=NOTION_API_KEY)

def fetch_all_jobs():
    results = notion.databases.query(database_id=NOTION_DB_ID)
    return results.get('results', [])

def compute_funnel_metrics(jobs):
    stage_counts = defaultdict(int)
    source_performance = defaultdict(lambda: {'total': 0, 'interviews': 0})

    for job in jobs:
        props = job['properties']
        status = props.get('Status', {}).get('select', {}).get('name', 'Unknown')
        source = props.get('Source', {}).get('select', {}).get('name', 'Unknown')
        stage_counts[status] += 1
        source_performance[source]['total'] += 1
        if status in ['Screen Scheduled', 'Interview', 'Final Round', 'Offer']:
            source_performance[source]['interviews'] += 1

    return stage_counts, source_performance

def generate_weekly_report(stage_counts, source_performance):
    today = datetime.now().strftime("%Y-%m-%d")
    report = f"""# Weekly Funnel Report — {today}

## Funnel Stages

| Stage | Count |
|-------|-------|
"""
    for stage, count in sorted(stage_counts.items()):
        report += f"| {stage} | {count} |\n"

    report += """

## Source Performance

| Source | Total | Interviews | Rate |
|--------|-------|------------|------|
"""
    for source, data in sorted(source_performance.items()):
        rate = (data['interviews'] / data['total'] * 100) if data['total'] > 0 else 0
        report += f"| {source} | {data['total']} | {data['interviews']} | {rate:.1f}% |\n"

    total_surfaced = sum(stage_counts.values())
    total_applied = stage_counts.get('Applied', 0) + stage_counts.get('Submitted', 0)
    total_interviews = sum(stage_counts.get(s, 0) for s in ['Screen Scheduled', 'Interview', 'Final Round'])
    apply_rate = (total_applied / total_surfaced * 100) if total_surfaced > 0 else 0
    interview_rate = (total_interviews / total_applied * 100) if total_applied > 0 else 0

    report += f"""

## Key Metrics

- **Jobs surfaced:** {total_surfaced}
- **Applications sent:** {total_applied} ({apply_rate:.1f}% of surfaced)
- **Interviews:** {total_interviews} ({interview_rate:.1f}% of applied)

## What to Do This Week

"""
    if interview_rate < 5:
        report += "1. **Low interview rate** — Review resume variants for authenticity\n"
    if apply_rate < 20:
        report += "1. **Low apply rate** — Expand search sources or lower scoring threshold\n"
    else:
        report += "1. **Funnel healthy** — Continue current process\n"

    report += "\n---\n*Auto-generated by Funnel Analyst Bot*\n"

    Path("reports").mkdir(exist_ok=True)
    with open(f"reports/weekly-{today}.md", "w") as f:
        f.write(report)
    return report

def main():
    print("📊 Running weekly funnel analysis...")
    jobs = fetch_all_jobs()
    print(f"✓ Loaded {len(jobs)} jobs from Notion")
    stage_counts, source_performance = compute_funnel_metrics(jobs)
    generate_weekly_report(stage_counts, source_performance)
    print(f"✓ Report saved to reports/weekly-{datetime.now().strftime('%Y-%m-%d')}.md")
    print("✅ Funnel analysis complete")

if __name__ == "__main__":
    main()
